first:
  datasource:
    password: root
    username: root
    jdbc-url: jdbc:mysql://localhost:3306/powerbusiness?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver

second:
  datasource:
    password: root
    username: root
    jdbc-url: jdbc:mysql://localhost:3306/drugs?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver